config/routes.rb
Wrobel::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :microposts, except: [:edit, :update]
  resources :messages, only: [:new, :create, :destroy]
  resources :favourites, only: [:create, :destroy]
  get 'tag/:name'     => "tags#show",        as: :tag
  get 'logout'        => "sessions#destroy", as: :logout
  get "about"         => "pages#about",      as: :about
  get 'terms'         => "pages#terms",      as: :terms
  get 'cookies_policy'=> "pages#cookies_p",  as: :cookies_policy
  get 'contact'       => "pages#contact",    as: :contact
  get 'mentions'      => "users#mentions",   as: :mentions
  get 'messages'      => "users#threads",    as: :threads
  get 'threads/:id'   => "threads#show",     as: :thread
  get ':name/new_msg' => "messages#new",     as: :new_msg
  get 'new'           => "users#new",        as: :new_user
  get 'search'        => "users#index",      as: :index_user
  root "pages#home"
  resources :users, except: [:new, :index], path: '/' do
    member do
      get :following, :followers, :favourites
    end
  end
  

  

end

app/models/user.rb
# encoding: utf-8

# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  email               :string(255)
#  password_digest     :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  auth_token          :string(255)
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  newmsgcount         :integer          default(0), not null
#  realname            :string(255)
#

class User < ActiveRecord::Base
  before_create { generate_token(:auth_token) }
  has_secure_password
  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>', small: '50x50>' }, default_url: '/user50.png'
  has_many :microposts, dependent: :destroy
  has_many :messages_received, class_name: 'Message',
                               foreign_key: 'to_user_id'
  has_many :messages_sent, class_name: 'Message',
                           foreign_key: 'from_user_id'
  has_many :relationships,
           foreign_key: 'follower_id',
           dependent: :destroy
  has_many :followed_users,
           through: :relationships, source: :followed
  has_many :reverse_relationships,
           foreign_key: 'followed_id',
           class_name: 'Relationship',
           dependent: :destroy
  has_many :followers,
           through: :reverse_relationships, source: :follower
  has_many :mentions, dependent: :destroy
  has_many :mentions_microposts, through: :mentions, source: :micropost
  has_many :recrumbed_posts,  class_name: 'Micropost',
                              foreign_key: 'recrumbed_by_id',
                              dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :favourite_microposts, through: :favourites,
                                  source: :micropost

  email_regex       = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  no_spaces_regex   = /\A[\S]+\z/

  validates_format_of :email, with: email_regex
  validates_format_of :name,  with: no_spaces_regex
  validates :email, presence: true
  validates :name, length: { maximum: 30 },
                   presence: true
  validates :password_confirmation, presence: true
  validates :password, presence: true
  validates_length_of :password, within: 6..30
  validates_length_of :realname, within: 3..40, allow_blank: true
  validates_uniqueness_of :name, case_sensitive: false
  validates_uniqueness_of :email, case_sensitive: false
  validate :reserved_name

  searchable do
    text :name
    text :realname
  end

  def feed
    Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    !!relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def mentions_count
    mentions.where('seen = ?', false).count
  end

  def reset_mentions_count
    mentions.where('seen = ?', false).update_all(seen: true)
  end

  def self.find_by_similar_name(name)
    where('name LIKE ?', name).first
  end

  def threads
    Message.user_threads(self)
  end

  def thread_exists?(user)
    Message.threads.where('(to_user_id = :cid AND from_user_id = :id) OR (to_user_id = :id AND from_user_id = :cid)', id: user.id, cid: id).any?
  end

  def thread_with(user)
    Message.threads.where('(to_user_id = :cid AND from_user_id = :id) OR (to_user_id = :id AND from_user_id = :cid)', id: user.id, cid: id).first
  end

  def increase_newmsgcount!
    increment!(:newmsgcount)
  end

  def decrease_newmsgcount!(l)
    decrement!(:newmsgcount, l)
  end

  def favourite?(mp)
    favourites.find_by(micropost_id: mp.id)
  end

  def favourite(mp)
    favourites.find_by(micropost_id: mp.id)
  end

  def generate_token(name)
    self[name] = SecureRandom.urlsafe_base64
    if User.exists?(name => self[name])
      generate_token(name)
    end
  end

  def self.find(input)
    input.to_i == 0 ? find_by_similar_name(input) : super
  end

  private
  require 'set'
  RESERVED_NAMES = Set.new(%w{
    about account add admin api
    app apps archive archives auth
    blog
    cookies_policy config connect contact create
    delete direct_messages downloads
    edit email
    faq favorites favourites feed feeds follow followers following
    help home
    invitations invite
    jobs
    login log-in log_in logout log-out log_out logs
    map maps mentions messages
    new_msg
    oauth oauth_clients openid
    privacy
    register remove replies rss
    save search sessions settings
    search signup sign-up sign_up signin sign-in sign_in signout sign-out sign_out
    sitemap ssl subscribe
    tag terms test threads trends
    unfollow unsubscribe url user
    widget widgets
    xfn xmpp
  })

  def reserved_name
    if RESERVED_NAMES.include?(name)
      errors[:name] << 'Imię zarezerwowane'
    end
  end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  before_action :not_logged_in, only: [:new, :create]
  before_action :logged_in,     only: [:edit, :update, :delete, :mentions]
  before_action :the_same_user, only: [:edit, :update, :delete]
  #actions above in sessions_helper
  
  def index
    require 'will_paginate/array'
    if params[:search]
      search = User.search{ fulltext params[:search] }.results.to_a
      @users = search.paginate(:page => params[:page])
      if @users.size == 1
        redirect_to user_path @users.first.name
      end
    else
      redirect_back_or root_path
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.where('recrumbed_id IS NULL').paginate(:page => params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      redirect_to root_path, notice: "Zarejestrowano i zalogowano"
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.authenticate(params[:user][:current_password])
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user][:password] = params[:user][:current_password]
        params[:user][:password_confirmation] = params[:user][:current_password]
      end
      params[:user].delete :current_password
      if @user.update_attributes(user_params)
        flash[:notice] = "Zaaktalizowano profil"
        redirect_to user_path @user.name
      else
        render 'edit'
      end
    else
      flash.now[:error] = "Nieprawidłowe hasło"
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.authenticate params[:user][:password]
      @user.destroy
      cookies.delete :auth_token
      flash[:notice] = "Usunięto konto"
      redirect_to root_path
    else
      flash[:error] = "Nieprawidłowe hasło"
      redirect_to edit_user_path @user.name
    end
  end

  def following
    @user = User.find params[:id]
    @title = "#{@user.name} obserwuje"
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @user = User.find params[:id]
    @title = "Obserwujący #{@user.name}"
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def mentions
    @user = current_user
    @mentions = @user.mentions.paginate(page: params[:page])
  end

  def threads
    @user = current_user
    @threads = @user.threads.sort_by { |a| a.latest_message }.reverse
  end

  def favourites
    @user = User.find params[:id]
    @microposts = @user.favourite_microposts.paginate(page: params[:page])
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, 
                                 :avatar, :realname)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_author.html.erb
<% if t.latest_message.from_user == current_user %>
  <%= "Ja" %>
<% else %>
  <%= t.latest_message.from_user.name %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.new(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Obserwuj", class: "btn btn-primary", 
      id:'follow' %>
<% end %>

app/views/users/_message.html.erb
<% if user.thread_exists? current_user %>
  <%= link_to thread_path(user.thread_with(current_user)) do %>
    <button id="msg" class="btn btn-success btn-small">
      <i class="icon-white icon-envelope"></i>
      Napisz wiadomość
    </button>
  <% end %> 
  <% else %>
  <%= link_to new_msg_path(user.name) do %>
    <button id="msg" class="btn btn-success btn-small">
      <i class="icon-white icon-envelope"></i>
      Napisz wiadomość
    </button>
  <% end %> 
<% end %>

app/views/users/_thread.html.erb
<% if t.to_user == current_user %>
  <%= link_to user_path(t.from_user.name) do %>
    <%= image_tag t.from_user.avatar.url(:small), 
    class:"mpimage" %>
    <div style="display:inline-block">
      <span class="username">
        <%= t.from_user.name %>
        <% if (t.receiver_new > 0 && 
        t.latest_message.to_user == current_user) %>
          <%= "(#{t.receiver_new})" %>
        <% end %>
      </span>
    </div>
  <% end %>
<% else %>
  <%= link_to user_path(t.to_user.name) do %>
    <%= image_tag t.to_user.avatar.url(:small), 
    class:"mpimage" %>
    <div style="display:inline-block">
      <span class="username">
        <%= t.to_user.name %>
        <% if (t.sender_new > 0 && 
        t.latest_message.to_user == current_user) %>
          <%= "(#{t.sender_new})" %>
        <% end %>
      </span>
    </div>
  <% end %>
<% end %>
Ostatnia wiadomość( autor:<%= render 'author', t:t %>)
<%= link_to thread_path(t.id) do %>
  <% if (t.receiver_new > 0 && 
    t.latest_message.to_user == current_user) || 
    (t.sender_new > 0 && 
    t.latest_message.to_user == current_user) %>
    <span class="content" style="font-weight: bold">
      <%= t.latest_message.body %>
    </span>
  <% else %>
    <span class="content">
      <%= t.latest_message.body %>
    </span>
  <% end %>
<% end %>
<span class="timestamp">
  <%= time_ago_in_words(t.latest_message.created_at) %> temu
</span>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Obserwuję", class: "btn btn-primary", 
      id: 'unfollow' %>
<% end %>

app/views/users/edit.html.erb
<% provide :title, "Edytuj profil" %>
<%= simple_form_for(@user, html: { class: 'form-horizontal form', multipart: true }) do |f| %>
  <%= f.input :name, label:"Nick" %>
  <%= f.input :email, placeholder:"example@domain.com" %>
  <%= f.input :realname, label:"Prawdziwe imię i nazwisko" %>
  <%= f.input :avatar, as: :file %>
  <%= f.input :current_password, label:"Aktualne hasło",
  required:true %>
  <%= f.input :password, label:"Nowe hasło", 
              hint:"Minimum 6 znaków", required: false %>
  <%= f.input :password_confirmation, 
          label:"Potwierdzenie", required: false %>
  <%= f.button :submit, "Zatwierdź",
   class: 'btn-primary' %>
<% end %>
<h3>
  Usuń konto
</h3>
<%= form_for(@user, html: { class: 'form-horizontal form', multipart: true }, method: :delete)  do |f| %>
  <%= f.label :password, "*Hasło:" %>
  <%= f.password_field :password %>
  <br>
  <%= f.submit "Usuń konto", class: "btn btn-danger", id:"takibutton" %>
<% end %>

app/views/users/favourites.html.erb
<% provide :title, "#{@user.name} | Ulubione" %>
<h3 class="center">Ulubione:</h3>
<ul class="microposts">
<% @microposts.each do |m| %>
  <%= tag("li", data: {mp_id: m.id, mp_from_id: 
      m.recrumbed_from_id}) %>
    <%= render "rend/micropost", micropost:m %>
  </li>
<% end %>
</ul>
<div class="center"><%= will_paginate @microposts %></div>

app/views/users/index.html.erb
<% provide :title, "Wyszukiwanie użytkownika #{params[:search]}" %>
<% if @users.any? %>
  <ul class='microposts'>
    <% @users.each do |u| %>
    <li>
      <%= link_to user_path(u.name) do %>
      <%= image_tag u.avatar.url(:thumb), 
      class:"mpimage" %>
      <div style="display:inline-block">
        <h3 class="username"><%= u.name %><h3>
      </div>
      <% end %>
    </li>
    <% end %>
  </ul>
  <div class="center"><%= will_paginate @users %></div>
<% else %>
<h2>
  Nie znaleziony użytkownika
</h2>
<% end %>

app/views/users/mentioned_micropost.html.erb
<%= link_to user_path(micropost.user.name) do %>
  <%= image_tag micropost.user.avatar.url(:small), 
      class:"mpimage" %>
  <div style="display:inline-block">
    <span class="username"><%= micropost.user.name %></span>
  </div>
<% end %>
<span class="content">
  <%= mcontent micropost %>
</span>
<span class="timestamp">
  <%= time_ago_in_words(micropost.created_at) %> temu
</span>

app/views/users/mentions.html.erb
<% provide :title, "Interakcje" %>
<h3 class="center">Interakcje:</h3>
<ul class="microposts">
<% @mentions.each do |m| %>
  <% if m.seen == false %>
    <li class="mentioned">
      <%= render "rend/micropost", micropost:m.micropost %>
    </li>
  <% else %>
    <li>
      <%= render "rend/micropost", micropost:m.micropost %>
    </li>
    <% end %>
<% end %>
</ul>
<div class="center"><%= will_paginate @mentions %></div>
<% current_user.reset_mentions_count %>

app/views/users/new.html.erb
<% provide :title, "Zarejestruj" %>
<%= simple_form_for(@user, html: { class: 'form-horizontal form' })  do |f| %>
  <%= f.input :name, label:"Nick (bez spacji)" %>
  <%= f.input :email, placeholder:"example@domain.com" %>
  <%= f.input :password, label:"Hasło", 
              hint:"Minimum 6 znaków" %>
  <%= f.input :password_confirmation, 
          label:"Potwierdzenie" %>
  <%= f.button :submit, "Zatwierdź",
   class: 'btn-primary' %>
<% end %>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<h1 class="center"><%= @user.name %></h1>
<% if @user.realname.present? %>
  <h5 class="center"><%= @user.realname %></h5>
<% end %>

<%= image_tag @user.avatar.url(:medium), style:"float:right" %>
<% if current_user %>
  <% if @user.following? current_user %>
    <%= render 'message', user: @user %>
  <% end %>
  <br>
  <% unless current_user == @user %>
    <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
    </div>
  <% end %>
<% end %>

<strong>Obserwuje:</strong>
<%= link_to following_user_path @user.name do %>
  <%= @user.followed_users.count %>
<% end %>
<br>
<strong>Obserwujący:</strong>

<%= link_to followers_user_path @user.name do %>
  <span id="followers">
    <%= @user.followers.count %>
  </span>
<% end %>

<br>
<strong>Liczba okruchów:</strong>
<%= @user.microposts.count %>
<br>
<h3 class="center" style="margin-top:150px;">Okruchy:</h3>
<ul class="microposts">
<% @microposts.each do |m| %>
  <%= tag("li", data: {mp_id: m.id, mp_from_id: 
      m.recrumbed_from_id}) %>
    <%= render "rend/micropost", micropost:m %>
  </li>
<% end %>
</ul>
<div class="center"><%= will_paginate @microposts %></div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<h3 class="center"><%= @title %></h3>
<% if @users.any? %>
  <ul class="users">
    <% @users.each do |p| %>
      <li>
        <%= link_to user_path(p) do %>
          <%= p.name %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="center"> 
    <%= will_paginate @users %>
  </div>
<% end %>

app/views/users/threads.html.erb
<% provide :title, "Lista wiadomości" %>
<% if @threads.empty? %>
  <h3 class="center">Nie masz żadnych wiadomości</h3>
<% end %>
<ul class="microposts">
  <% @threads.each do |t| %>
    <li>
      <%= render "thread", t:t %>
    </li>
  <% end %>
</ul>