config/routes.rb
Wrobel::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :microposts, except: [:edit, :update]
  resources :messages, only: [:new, :create, :destroy]
  resources :favourites, only: [:create, :destroy]
  get 'tag/:name'     => "tags#show",        as: :tag
  get 'logout'        => "sessions#destroy", as: :logout
  get "about"         => "pages#about",      as: :about
  get 'terms'         => "pages#terms",      as: :terms
  get 'cookies_policy'=> "pages#cookies_p",  as: :cookies_policy
  get 'contact'       => "pages#contact",    as: :contact
  get 'mentions'      => "users#mentions",   as: :mentions
  get 'messages'      => "users#threads",    as: :threads
  get 'threads/:id'   => "threads#show",     as: :thread
  get ':name/new_msg' => "messages#new",     as: :new_msg
  get 'new'           => "users#new",        as: :new_user
  get 'search'        => "users#index",      as: :index_user
  root "pages#home"
  resources :users, except: [:new, :index], path: '/' do
    member do
      get :following, :followers, :favourites
    end
  end
  

  

end

app/views/rend/_delete_micropost.html.erb
<%= link_to micropost_path(micropost), method: :delete, id: "delete", title:"Usuń" do %>
  <i class='icon-remove'></i>
<% end %>

app/views/rend/_favourite.html.erb
<%= form_for current_user.favourites.new(micropost_id:
micropost.recrumbed_id || micropost.id), remote: true do |f| %>
  <%= f.hidden_field :micropost_id %>
  <%= button_tag(type: "submit", 
      class:"btn btn-warning btn-small favouriteb") do %>
    <i class:"icon-heart"></i>
    Dodaj do ulubionych
  <% end %>
<% end %>

app/views/rend/_micropost.html.erb
<!-- Do zaimplementowania link do mikropostu -->

<%= link_to user_path(micropost.user.name) do %>
  <%= image_tag micropost.user.avatar.url(:small), 
      class:"mpimage" %>
  <div style="display:inline-block">
    <span class="username"><%= micropost.user.name %></span>
  </div>
<% end %>
<% if micropost.user == current_user && !micropost.recrumbed_id %>
  <%= render 'rend/delete_micropost', micropost: micropost %>
<% end %>
<span class="content">
  <%= mcontent micropost %>
</span>
<span class="timestamp">
  <%= time_ago_in_words(micropost.created_at) %> temu
</span>
<% if current_user && current_user.favourite?(micropost) %>
  <span class="favourite">
    &#9733;Ulubiony
  </span>
<% end %>
<% if micropost.recrumbed_by_id %>
  Ziarno przekazane przez: 
  <%= link_to user_path(User.find(micropost.recrumbed_by_id).name) do %>
    <%= User.find(micropost.recrumbed_by_id).name %>
  <% end %>
<% end %>
<div id="reaction" class="row-fluid">
<% if current_user && micropost.user != current_user %>
  <div id="recrumb">
  <% unless micropost.recrumbed?(current_user).first %>
    <%= render 'rend/recrumb_form', micropost: micropost %>
  <% else %>
      <%= render 'rend/unrecrumb_form', micropost: micropost %>
  <% end %>
  </div>
  <div id="favourite_form">
  <% if current_user.favourite?(micropost) %>
    <%= render 'rend/unfavourite', micropost: micropost %>
  <% else %>
    <%= render 'rend/favourite', micropost: micropost %>
  <% end %>
  </div>
  <div class="reply_button">
    <button class="btn btn-small btn-primary reply">
      <i class="icon-share"></i>
      Odpowiedz
    </button>
  </div>
  <div id="reply_form" class="center hiddenmy">
    <%= render 'rend/reply_form', micropost: micropost %>
  </div>
<% end %>
</div>

app/views/rend/_recrumb_form.html.erb
<%= form_for current_user.microposts.
new(recrumbed_id: micropost.recrumbed_id || micropost.id, recrumbed_from_id: micropost.id),html:{id:"recrumb"}, remote:true do |f| %>
  <%= f.hidden_field :recrumbed_id %>
  <%= f.hidden_field :recrumbed_from_id %>
  <%= button_tag(type: 'submit', 
  class:'btn btn-info btn-small recrumb') do %>
    <i class='icon-refresh'></i>
    Przekaż ziarno
  <% end %>
<% end %>

app/views/rend/_reply_form.html.erb
<%= simple_form_for micropost.replies.new, 
    html: { id: 'micropost_reply' } do |f| %>
  <%= f.input :content, as: :text, label: false, 
         input_html: { value: "@#{micropost.user.name} ", class:"span12 repfrm" } %>
  <%= f.hidden_field :thread_id, value: micropost.id %>
  <%= f.button :submit, "Odpowiedz", 
                        class: "btn-primary repbtn" %>
<% end %>

app/views/rend/_search_form.html.erb
<div style="float:right">
<%= form_tag index_user_path, method: :get, id: 'sform' do %>
  <%= text_field_tag :search, params[:search], 
      placeholder: "Wyszukaj użytkownika" %>
<% end %>
</div>

app/views/rend/_session_form.html.erb
<h3>Zaloguj się</h3>
<%= simple_form_for :session, url: sessions_path, 
    html: { class: 'form-vertical' } do |f| %>
  <%= f.input :email, placeholder: 'e-mail',
  label: false %>
  <%= f.input :password, placeholder: 'hasło',
              label: false %>
  <%= f.input :remember_me, as: :boolean, 
    inline_label: "Zapamiętaj mnie", label: false %>
    <%= f.button :submit, "Zaloguj się",
   class: 'btn-primary' %>
<% end %>

app/views/rend/_unfavourite.html.erb
<%= link_to favourite_path(current_user.favourite(micropost)), method: :delete, remote: true do %>
<button class='btn btn-warning btn-small unfavourite'>
  <i class:"icon-heart"></i>
  Dodano do ulubionych
</button>
<% end %>

app/views/rend/_unfavourite_js.html.erb
<%= link_to favourite_path(current_user.favourite(micropost)), method: :delete, remote: true do %>
<button class='btn btn-danger btn-small unfavourite'>
  <i class:"icon-heart"></i>
  Usuń ulubionych
</button>
<% end %>

app/views/rend/_unrecrumb_form.html.erb
<%= link_to micropost_path(micropost.recrumbed?(current_user).first), method: :delete, remote:true do %>
  <button class='btn btn-info btn-small unrecrumb'>
  <i class='icon-refresh'></i> Przekazałeś ziarno
</button>
<% end %>

app/views/rend/_unrecrumb_form_js.html.erb
<%= link_to micropost_path(micropost.recrumbed?(current_user).first), method: :delete, remote:true do %>
  <button class='btn btn-danger btn-small unrecrumb'>
  <i class='icon-refresh'></i> Przestań przekazywać
</button>
<% end %>

app/views/rend/_user_panel.html.erb
Zalogowany jako <%= link_to user_path(current_name) do%>
<strong><%= current_name %></strong>
<% end %><br>
<ul class="navbar unstyled">
  <li>
    <%= link_to mentions_path do %>
      <%= "Interakcje" %>
      <%= "#{current_user.mentions_count > 0 ? 
             %'(#{current_user.mentions_count})' : ''}" %>
    <% end %>
  </li>
  <li><%= link_to threads_path  do %>
    <%= "Wiadomości" %>
    <%= "#{current_user.newmsgcount > 0 ? 
             %'(#{current_user.newmsgcount})' : ''}" %>
  <% end %>
  </li>
  <li>
    <%= link_to "Ulubione", 
                favourites_user_path(current_name) %>
  </li>
  <li><%= link_to "Edytuj profil", 
          edit_user_path(current_name) %></li>
  <li><%= link_to "Wyloguj się", logout_path %></li>
</ul>