config/routes.rb
Wrobel::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :microposts, except: [:edit, :update]
  resources :messages, only: [:new, :create, :destroy]
  resources :favourites, only: [:create, :destroy]
  get 'tag/:name'     => "tags#show",        as: :tag
  get 'logout'        => "sessions#destroy", as: :logout
  get "about"         => "pages#about",      as: :about
  get 'terms'         => "pages#terms",      as: :terms
  get 'cookies_policy'=> "pages#cookies_p",  as: :cookies_policy
  get 'contact'       => "pages#contact",    as: :contact
  get 'mentions'      => "users#mentions",   as: :mentions
  get 'messages'      => "users#threads",    as: :threads
  get 'threads/:id'   => "threads#show",     as: :thread
  get ':name/new_msg' => "messages#new",     as: :new_msg
  get 'new'           => "users#new",        as: :new_user
  get 'search'        => "users#index",      as: :index_user
  root "pages#home"
  resources :users, except: [:new, :index], path: '/' do
    member do
      get :following, :followers, :favourites
    end
  end
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? "Wróbel | #{yield :title}" : "Wróbel" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Wróbel</a>
          <div class="container-fluid nav-collapse">
            <%= render 'rend/search_form' %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <% if current_user %>
              <%= render 'rend/user_panel' %>
            <% else %>
              <%= render 'rend/session_form' %>
            <% end %>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p class="center">&copy; Wróbel 2013</p>
        <ul class="center" id="footer_list">
          <li><%= link_to "O", about_path %></li>
          <li><%= link_to "Regulamin", terms_path %></li>
          <li>
            <%= link_to "Ciasteczka", cookies_policy_path  %>
          </li>
          <li><%= link_to "Kontakt", contact_path %></li>
        </ul>
      </footer>
      <%= debug(params) if Rails.env.development? %>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>